### ISSUE TITLE
Ability to create/delete rows from UI

### ISSUE THREAD

**Issue by bbenefield89** [bbenefield89/express-admin-area#17]
### Expected Behavior
Users should be able to create/delete a single row from the database using the UI.

### Actual Behavior
No way to create/delete a row using the UI

### Screenshot

# Tasks
- Create new row (**bbenefield89**)
  - [x] Create Component
  - [x] Successfully send request to create new row in DB
  - [x] Display new data to client
  - [x] Check for SQLi (**PASS**)
  - [x] Write unit tests
  - [x] Optimize/Refactor
- Delete existing row
  - [x] Create Component
  - [x] Successfully send request to delete existing row from DB
  - [x] Display new data to client
  - [x] Write unit tests
  - [x] Optimize/Refactor
